-- Databricks notebook source
-- MAGIC %md
-- MAGIC # Lending Club loan default risk - SQL pipeline (Databricks SQL)
-- MAGIC Generated by `scripts/build_databricks.py` from `sql/` (same Spark-dialect SQL that runs locally on DuckDB).
-- MAGIC
-- MAGIC 1. Upload the raw files to the Unity Catalog volume `/Volumes/workspace/da_learn_04/raw` (see `databricks/SETUP.md`).
-- MAGIC 2. Attach to a SQL warehouse (or DBR 13.3+ cluster) and *Run all*.
-- MAGIC 3. Cells: config -> staging (`read_files`) -> 02 cleaning -> 03 star schema -> 04 KPIs -> 05 data-quality -> visualization queries.

-- COMMAND ----------

-- Config: change catalog / schema here (and in the dashboard JSON) if needed
CREATE SCHEMA IF NOT EXISTS workspace.da_learn_04;
USE CATALOG workspace;
USE SCHEMA da_learn_04;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## 01 Staging - all columns as STRING (`inferColumnTypes => false`), typing happens in 02

-- COMMAND ----------

CREATE OR REPLACE TABLE stg_loans AS
SELECT id, member_id, loan_amnt, funded_amnt, funded_amnt_inv, term, int_rate, installment, grade, sub_grade, emp_length, home_ownership, annual_inc, verification_status, issue_d, loan_status, purpose, addr_state, dti, delinq_2yrs, earliest_cr_line, inq_last_6mths, open_acc, pub_rec, revol_bal, revol_util, total_acc, total_pymnt, total_rec_prncp, total_rec_int, recoveries, pub_rec_bankruptcies
FROM read_files('/Volumes/workspace/da_learn_04/raw/loan.csv',
  format => 'csv', header => true, multiLine => true, escape => '"', inferColumnTypes => false);

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## 02 Cleaning (`sql/02_cleaning.sql`)

-- COMMAND ----------

-- 02_cleaning.sql  Typed, standardised, de-duplicated loans (Spark SQL dialect; DuckDB via 00 shims)

CREATE OR REPLACE TABLE cln_loans_typed AS
SELECT
  TRY_CAST(trim(id) AS BIGINT)                                        AS loan_id,
  TRY_CAST(trim(member_id) AS BIGINT)                                 AS member_id,
  TRY_CAST(trim(loan_amnt) AS DOUBLE)                                 AS loan_amount,
  TRY_CAST(trim(funded_amnt) AS DOUBLE)                               AS funded_amount,
  TRY_CAST(trim(funded_amnt_inv) AS DOUBLE)                           AS funded_amount_investors,
  TRY_CAST(trim(replace(term, 'months', '')) AS INT)                  AS term_months,
  TRY_CAST(trim(replace(int_rate, '%', '')) AS DOUBLE)                AS int_rate_pct,
  TRY_CAST(trim(installment) AS DOUBLE)                               AS installment,
  upper(trim(grade))                                                  AS grade,
  upper(trim(sub_grade))                                              AS sub_grade,
  CASE WHEN trim(emp_length) = '< 1 year' THEN 0
       WHEN trim(emp_length) = '10+ years' THEN 10
       ELSE TRY_CAST(trim(replace(replace(emp_length, 'years', ''), 'year', '')) AS INT) END AS emp_length_years,
  CASE WHEN upper(trim(home_ownership)) IN ('RENT', 'MORTGAGE', 'OWN') THEN upper(trim(home_ownership))
       ELSE 'OTHER' END                                               AS home_ownership,
  TRY_CAST(trim(annual_inc) AS DOUBLE)                                AS annual_income,
  CASE WHEN trim(verification_status) = 'Not Verified' THEN 'Not verified'
       WHEN trim(verification_status) = 'Source Verified' THEN 'Source verified'
       ELSE 'Verified' END                                            AS verification_status,
  make_date(2000 + TRY_CAST(substr(trim(issue_d), 5, 2) AS INT),
            CAST((instr('JanFebMarAprMayJunJulAugSepOctNovDec', substr(trim(issue_d), 1, 3)) + 2) / 3 AS INT), 1) AS issue_month,
  trim(loan_status)                                                   AS loan_status,
  lower(trim(purpose))                                                AS purpose,
  upper(trim(addr_state))                                             AS state,
  TRY_CAST(trim(dti) AS DOUBLE)                                       AS dti,
  TRY_CAST(trim(delinq_2yrs) AS INT)                                  AS delinq_2yrs,
  make_date(CASE WHEN TRY_CAST(substr(trim(earliest_cr_line), 5, 2) AS INT) > 11
                 THEN 1900 ELSE 2000 END + TRY_CAST(substr(trim(earliest_cr_line), 5, 2) AS INT),
            CAST((instr('JanFebMarAprMayJunJulAugSepOctNovDec', substr(trim(earliest_cr_line), 1, 3)) + 2) / 3 AS INT), 1) AS earliest_credit_line,
  TRY_CAST(trim(inq_last_6mths) AS INT)                               AS inquiries_6m,
  TRY_CAST(trim(open_acc) AS INT)                                     AS open_accounts,
  TRY_CAST(trim(pub_rec) AS INT)                                      AS public_records,
  TRY_CAST(trim(revol_bal) AS DOUBLE)                                 AS revolving_balance,
  TRY_CAST(trim(replace(revol_util, '%', '')) AS DOUBLE)              AS revolving_util_pct,
  TRY_CAST(trim(total_acc) AS INT)                                    AS total_accounts,
  ROUND(TRY_CAST(trim(total_pymnt) AS DOUBLE), 2)                     AS total_payment,
  ROUND(TRY_CAST(trim(total_rec_prncp) AS DOUBLE), 2)                 AS principal_received,
  ROUND(TRY_CAST(trim(total_rec_int) AS DOUBLE), 2)                   AS interest_received,
  ROUND(TRY_CAST(trim(recoveries) AS DOUBLE), 2)                      AS recoveries,
  TRY_CAST(trim(pub_rec_bankruptcies) AS INT)                         AS bankruptcies
FROM stg_loans;

-- COMMAND ----------

-- Dedupe on loan_id (keep one row per id) and drop rows without the fields every metric needs

CREATE OR REPLACE TABLE cln_loans_dedup AS
SELECT * FROM (
  SELECT *, ROW_NUMBER() OVER (PARTITION BY loan_id ORDER BY issue_month DESC, funded_amount DESC) AS rn
  FROM cln_loans_typed
  WHERE loan_id IS NOT NULL AND funded_amount > 0 AND grade IS NOT NULL AND issue_month IS NOT NULL
    AND loan_status IN ('Fully Paid', 'Charged Off', 'Current')
) x WHERE rn = 1;

-- COMMAND ----------

CREATE OR REPLACE TABLE cln_income_bounds AS
SELECT percentile(annual_income, 0.25) AS q1, percentile(annual_income, 0.75) AS q3
FROM cln_loans_dedup;

-- COMMAND ----------

-- principal written off on charged-off loans (funded - principal repaid - recoveries)

CREATE OR REPLACE TABLE cln_loans AS
SELECT
  d.loan_id, d.member_id, d.loan_amount, d.funded_amount, d.funded_amount_investors, d.term_months, d.int_rate_pct,
  d.installment, d.grade, d.sub_grade,
  CAST(substr(d.sub_grade, 2, 1) AS INT)                              AS sub_grade_step,
  d.emp_length_years,
  CASE WHEN d.emp_length_years IS NULL THEN 'Unknown'
       WHEN d.emp_length_years < 2 THEN '0-1 yrs'
       WHEN d.emp_length_years < 5 THEN '2-4 yrs'
       WHEN d.emp_length_years < 10 THEN '5-9 yrs'
       ELSE '10+ yrs' END                                             AS emp_length_band,
  d.home_ownership, d.annual_income,
  CASE WHEN d.annual_income < 30000 THEN '1: <30k'
       WHEN d.annual_income < 50000 THEN '2: 30-50k'
       WHEN d.annual_income < 75000 THEN '3: 50-75k'
       WHEN d.annual_income < 100000 THEN '4: 75-100k'
       WHEN d.annual_income < 150000 THEN '5: 100-150k'
       ELSE '6: 150k+' END                                            AS income_band,
  d.verification_status, d.issue_month, YEAR(d.issue_month) AS issue_year, d.loan_status, d.purpose,
  concat(upper(substr(d.purpose, 1, 1)), substr(replace(d.purpose, '_', ' '), 2)) AS purpose_label,
  d.state, d.dti,
  CASE WHEN d.dti < 5 THEN '1: 0-5'
       WHEN d.dti < 10 THEN '2: 5-10'
       WHEN d.dti < 15 THEN '3: 10-15'
       WHEN d.dti < 20 THEN '4: 15-20'
       WHEN d.dti < 25 THEN '5: 20-25'
       ELSE '6: 25-30' END                                            AS dti_band,
  d.delinq_2yrs, d.earliest_credit_line,
  CAST(FLOOR(datediff(d.issue_month, d.earliest_credit_line) / 365.25) AS INT) AS credit_history_years,
  d.inquiries_6m, d.open_accounts, d.public_records, d.revolving_balance, d.revolving_util_pct, d.total_accounts,
  d.total_payment, d.principal_received, d.interest_received, d.recoveries, d.bankruptcies,
  CASE WHEN d.loan_status = 'Current' THEN 0 ELSE 1 END              AS is_completed,
  CASE WHEN d.loan_status = 'Charged Off' THEN 1 ELSE 0 END          AS is_default,
  CASE WHEN d.loan_status = 'Charged Off'
       THEN ROUND(GREATEST(d.funded_amount - d.principal_received - d.recoveries, 0), 2) ELSE 0 END AS principal_loss,
  ROUND(d.installment * 12 / NULLIF(d.annual_income, 0) * 100, 2)    AS installment_to_income_pct,
  CASE WHEN d.annual_income > b.q3 + 3 * (b.q3 - b.q1) THEN 1 ELSE 0 END AS is_income_outlier_iqr3,
  CASE WHEN d.emp_length_years IS NULL THEN 1 ELSE 0 END             AS dq_missing_emp_length,
  CASE WHEN d.revolving_util_pct IS NULL THEN 1 ELSE 0 END           AS dq_missing_revol_util
FROM cln_loans_dedup d CROSS JOIN cln_income_bounds b;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## 03 Star schema (`sql/03_model.sql`)

-- COMMAND ----------

-- 03_model.sql  Star schema: fact_loan + dim_date (issue month), dim_grade, dim_purpose, dim_geography, dim_borrower

CREATE OR REPLACE TABLE dim_date AS
SELECT
  YEAR(issue_month) * 100 + MONTH(issue_month) AS month_key,
  issue_month                                     AS month_start,
  YEAR(issue_month)                               AS year,
  QUARTER(issue_month)                            AS quarter,
  MONTH(issue_month)                              AS month,
  concat(CAST(YEAR(issue_month) AS STRING), '-', lpad(CAST(MONTH(issue_month) AS STRING), 2, '0')) AS year_month
FROM (SELECT DISTINCT issue_month FROM cln_loans) d;

-- COMMAND ----------

CREATE OR REPLACE TABLE dim_grade AS
SELECT
  ROW_NUMBER() OVER (ORDER BY sub_grade)          AS grade_key,
  sub_grade, grade,
  instr('ABCDEFG', grade)                         AS grade_rank,
  sub_grade_step
FROM (SELECT DISTINCT sub_grade, grade, sub_grade_step FROM cln_loans) g;

-- COMMAND ----------

CREATE OR REPLACE TABLE dim_purpose AS
SELECT ROW_NUMBER() OVER (ORDER BY purpose) AS purpose_key, purpose, purpose_label
FROM (SELECT DISTINCT purpose, purpose_label FROM cln_loans) p;

-- COMMAND ----------

-- US state -> Census region (50 states + DC)

CREATE OR REPLACE TABLE dim_geography AS
SELECT ROW_NUMBER() OVER (ORDER BY state) AS geo_key, state,
  CASE WHEN state IN ('CT','ME','MA','NH','RI','VT','NJ','NY','PA') THEN 'Northeast'
       WHEN state IN ('IL','IN','MI','OH','WI','IA','KS','MN','MO','NE','ND','SD') THEN 'Midwest'
       WHEN state IN ('DE','DC','FL','GA','MD','NC','SC','VA','WV','AL','KY','MS','TN','AR','LA','OK','TX') THEN 'South'
       WHEN state IN ('AZ','CO','ID','MT','NV','NM','UT','WY','AK','CA','HI','OR','WA') THEN 'West'
       ELSE 'Unknown' END AS census_region
FROM (SELECT DISTINCT state FROM cln_loans) s;

-- COMMAND ----------

-- Junk dimension: borrower profile attributes captured at application

CREATE OR REPLACE TABLE dim_borrower AS
SELECT ROW_NUMBER() OVER (ORDER BY home_ownership, verification_status, emp_length_band, income_band) AS borrower_key,
       home_ownership, verification_status, emp_length_band, income_band
FROM (SELECT DISTINCT home_ownership, verification_status, emp_length_band, income_band FROM cln_loans) b;

-- COMMAND ----------

CREATE OR REPLACE TABLE fact_loan AS
SELECT
  l.loan_id,
  YEAR(l.issue_month) * 100 + MONTH(l.issue_month) AS issue_month_key,
  g.grade_key, p.purpose_key, geo.geo_key, b.borrower_key,
  l.term_months, l.loan_amount, l.funded_amount, l.int_rate_pct, l.installment,
  l.annual_income, l.dti, l.dti_band, l.revolving_util_pct, l.credit_history_years, l.inquiries_6m,
  l.delinq_2yrs, l.public_records, l.loan_status, l.is_completed, l.is_default,
  l.total_payment, l.principal_received, l.interest_received, l.recoveries, l.principal_loss,
  l.is_income_outlier_iqr3
FROM cln_loans l
LEFT JOIN dim_grade g ON l.sub_grade = g.sub_grade
LEFT JOIN dim_purpose p ON l.purpose = p.purpose
LEFT JOIN dim_geography geo ON l.state = geo.state
LEFT JOIN dim_borrower b ON l.home_ownership = b.home_ownership AND l.verification_status = b.verification_status
                         AND l.emp_length_band = b.emp_length_band AND l.income_band = b.income_band;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## 04 Business KPIs (`sql/04_analysis.sql`)

-- COMMAND ----------

-- 04_analysis.sql  Business KPIs (Spark SQL dialect)

CREATE OR REPLACE TABLE a_kpi_headline AS
SELECT
  COUNT(*)                                                                     AS loans,
  SUM(is_completed)                                                            AS completed_loans,
  SUM(1 - is_completed)                                                        AS current_loans,
  SUM(is_default)                                                              AS defaults,
  ROUND(100.0 * SUM(is_default) / SUM(is_completed), 2)                        AS default_rate_pct,
  ROUND(SUM(funded_amount), 0)                                                 AS funded_total,
  ROUND(AVG(funded_amount), 0)                                                 AS avg_funded_amount,
  ROUND(AVG(int_rate_pct), 2)                                                  AS avg_int_rate_pct,
  ROUND(median(annual_income), 0)                                              AS median_annual_income,
  ROUND(median(dti), 2)                                                        AS median_dti,
  ROUND(100.0 * SUM(CASE WHEN term_months = 60 THEN 1 ELSE 0 END) / COUNT(*), 2) AS pct_60_month,
  ROUND(SUM(principal_loss), 0)                                                AS principal_lost,
  ROUND(100.0 * SUM(principal_loss) / SUM(CASE WHEN is_completed = 1 THEN funded_amount END), 2) AS loss_rate_pct,
  ROUND(100.0 * (SUM(CASE WHEN is_completed = 1 THEN total_payment END)
               - SUM(CASE WHEN is_completed = 1 THEN funded_amount END))
        / SUM(CASE WHEN is_completed = 1 THEN funded_amount END), 2)           AS net_return_pct,
  MIN(issue_month)                                                             AS first_issue_month,
  MAX(issue_month)                                                             AS last_issue_month
FROM cln_loans;

-- COMMAND ----------

-- Q1: How does default risk scale with Lending Club's grade, and is the interest rate enough to pay for it?

CREATE OR REPLACE TABLE a_default_by_grade AS
SELECT grade, instr('ABCDEFG', grade) AS grade_rank,
       COUNT(*) AS loans, SUM(is_default) AS defaults,
       ROUND(100.0 * SUM(is_default) / COUNT(*), 2)                               AS default_rate_pct,
       ROUND(AVG(int_rate_pct), 2)                                                AS avg_int_rate_pct,
       ROUND(SUM(funded_amount), 0)                                               AS funded,
       ROUND(SUM(principal_loss), 0)                                              AS principal_loss,
       ROUND(100.0 * (SUM(total_payment) - SUM(funded_amount)) / SUM(funded_amount), 2) AS net_return_pct
FROM cln_loans WHERE is_completed = 1
GROUP BY grade;

-- COMMAND ----------

CREATE OR REPLACE TABLE a_default_by_subgrade AS
SELECT sub_grade, grade, COUNT(*) AS loans,
       ROUND(100.0 * SUM(is_default) / COUNT(*), 2) AS default_rate_pct,
       ROUND(AVG(int_rate_pct), 2)                  AS avg_int_rate_pct
FROM cln_loans WHERE is_completed = 1
GROUP BY sub_grade, grade;

-- COMMAND ----------

-- Q2: Which loan purposes default most?

CREATE OR REPLACE TABLE a_default_by_purpose AS
SELECT purpose, purpose_label, COUNT(*) AS loans, SUM(is_default) AS defaults,
       ROUND(100.0 * SUM(is_default) / COUNT(*), 2)                        AS default_rate_pct,
       ROUND(AVG(funded_amount), 0)                                         AS avg_funded_amount,
       ROUND(AVG(int_rate_pct), 2)                                          AS avg_int_rate_pct,
       ROUND(SUM(principal_loss), 0)                                        AS principal_loss
FROM cln_loans WHERE is_completed = 1
GROUP BY purpose, purpose_label;

-- COMMAND ----------

-- Q3: Does income protect against default?

CREATE OR REPLACE TABLE a_default_by_income AS
SELECT income_band, COUNT(*) AS loans,
       ROUND(100.0 * SUM(is_default) / COUNT(*), 2) AS default_rate_pct,
       ROUND(median(annual_income), 0)              AS median_income,
       ROUND(AVG(funded_amount), 0)                 AS avg_funded_amount,
       ROUND(AVG(installment_to_income_pct), 2)     AS avg_installment_to_income_pct
FROM cln_loans WHERE is_completed = 1
GROUP BY income_band;

-- COMMAND ----------

-- Q4: Does debt-to-income (DTI) predict default?

CREATE OR REPLACE TABLE a_default_by_dti AS
SELECT dti_band, COUNT(*) AS loans,
       ROUND(100.0 * SUM(is_default) / COUNT(*), 2) AS default_rate_pct,
       ROUND(AVG(dti), 2)                           AS avg_dti,
       ROUND(AVG(int_rate_pct), 2)                  AS avg_int_rate_pct
FROM cln_loans WHERE is_completed = 1
GROUP BY dti_band;

-- COMMAND ----------

-- Q5: Is DTI still informative once grade is known? (grade x DTI band)

CREATE OR REPLACE TABLE a_grade_dti_matrix AS
SELECT grade, dti_band, COUNT(*) AS loans,
       ROUND(100.0 * SUM(is_default) / COUNT(*), 2) AS default_rate_pct
FROM cln_loans WHERE is_completed = 1
GROUP BY grade, dti_band;

-- COMMAND ----------

-- Q6: Term and other borrower attributes

CREATE OR REPLACE TABLE a_default_by_profile AS
SELECT 'term' AS attribute, CONCAT(CAST(term_months AS STRING), ' months') AS value, COUNT(*) AS loans,
       ROUND(100.0 * SUM(is_default) / COUNT(*), 2) AS default_rate_pct
FROM cln_loans WHERE is_completed = 1 GROUP BY term_months
UNION ALL
SELECT 'home_ownership', home_ownership, COUNT(*), ROUND(100.0 * SUM(is_default) / COUNT(*), 2)
FROM cln_loans WHERE is_completed = 1 GROUP BY home_ownership
UNION ALL
SELECT 'verification_status', verification_status, COUNT(*), ROUND(100.0 * SUM(is_default) / COUNT(*), 2)
FROM cln_loans WHERE is_completed = 1 GROUP BY verification_status
UNION ALL
SELECT 'emp_length', emp_length_band, COUNT(*), ROUND(100.0 * SUM(is_default) / COUNT(*), 2)
FROM cln_loans WHERE is_completed = 1 GROUP BY emp_length_band
UNION ALL
SELECT 'public_record', CASE WHEN public_records > 0 THEN 'has record' ELSE 'none' END, COUNT(*),
       ROUND(100.0 * SUM(is_default) / COUNT(*), 2)
FROM cln_loans WHERE is_completed = 1 GROUP BY CASE WHEN public_records > 0 THEN 'has record' ELSE 'none' END
UNION ALL
SELECT 'inquiries_6m', CASE WHEN inquiries_6m >= 3 THEN '3+' ELSE CAST(inquiries_6m AS STRING) END, COUNT(*),
       ROUND(100.0 * SUM(is_default) / COUNT(*), 2)
FROM cln_loans WHERE is_completed = 1 GROUP BY CASE WHEN inquiries_6m >= 3 THEN '3+' ELSE CAST(inquiries_6m AS STRING) END;

-- COMMAND ----------

-- Q7: Vintage view - volume growth and default rate by issue year

CREATE OR REPLACE TABLE a_vintage AS
SELECT issue_year, COUNT(*) AS loans, ROUND(SUM(funded_amount), 0) AS funded,
       SUM(is_completed) AS completed_loans,
       ROUND(100.0 * SUM(is_default) / SUM(is_completed), 2) AS default_rate_pct,
       ROUND(AVG(int_rate_pct), 2) AS avg_int_rate_pct,
       ROUND(100.0 * SUM(CASE WHEN term_months = 60 THEN 1 ELSE 0 END) / COUNT(*), 2) AS pct_60_month
FROM cln_loans GROUP BY issue_year;

-- COMMAND ----------

CREATE OR REPLACE TABLE a_monthly_issuance AS
SELECT d.year_month, d.month_start, COUNT(*) AS loans, ROUND(SUM(f.funded_amount), 0) AS funded
FROM fact_loan f JOIN dim_date d ON f.issue_month_key = d.month_key
GROUP BY d.year_month, d.month_start;

-- COMMAND ----------

-- Q8: Geography - states with at least 500 completed loans

CREATE OR REPLACE TABLE a_state_default AS
SELECT g.state, g.census_region, COUNT(*) AS loans,
       ROUND(100.0 * SUM(f.is_default) / COUNT(*), 2) AS default_rate_pct
FROM fact_loan f JOIN dim_geography g ON f.geo_key = g.geo_key
WHERE f.is_completed = 1
GROUP BY g.state, g.census_region
HAVING COUNT(*) >= 500;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## 05 Data-quality checks (`sql/05_quality_checks.sql`)

-- COMMAND ----------

-- 05_quality_checks.sql  Data-quality evidence (Spark SQL dialect): before/after counts, null rates, issues, assertions

CREATE OR REPLACE TABLE dq_row_counts AS
SELECT 'loans' AS entity, (SELECT COUNT(*) FROM stg_loans) AS raw_rows,
       (SELECT COUNT(DISTINCT id) FROM stg_loans) AS distinct_keys,
       (SELECT COUNT(*) FROM cln_loans) AS clean_rows, 'loan (id)' AS grain
UNION ALL SELECT 'fact_loan', NULL, NULL, (SELECT COUNT(*) FROM fact_loan), 'loan'
UNION ALL SELECT 'dim_date', NULL, NULL, (SELECT COUNT(*) FROM dim_date), 'issue month'
UNION ALL SELECT 'dim_grade', NULL, NULL, (SELECT COUNT(*) FROM dim_grade), 'sub-grade'
UNION ALL SELECT 'dim_purpose', NULL, NULL, (SELECT COUNT(*) FROM dim_purpose), 'purpose'
UNION ALL SELECT 'dim_geography', NULL, NULL, (SELECT COUNT(*) FROM dim_geography), 'state'
UNION ALL SELECT 'dim_borrower', NULL, NULL, (SELECT COUNT(*) FROM dim_borrower), 'home x verification x emp band x income band';

-- COMMAND ----------

CREATE OR REPLACE TABLE dq_null_rates AS
SELECT 'loans' AS entity, 'emp_length' AS column_name,
  (SELECT ROUND(100.0 * SUM(CASE WHEN emp_length IS NULL OR trim(emp_length) IN ('', 'n/a') THEN 1 ELSE 0 END) / COUNT(*), 3) FROM stg_loans) AS raw_null_pct,
  (SELECT ROUND(100.0 * SUM(CASE WHEN emp_length_years IS NULL THEN 1 ELSE 0 END) / COUNT(*), 3) FROM cln_loans) AS clean_null_pct,
  'n/a -> NULL, reported as band Unknown' AS treatment
UNION ALL SELECT 'loans', 'revol_util',
  (SELECT ROUND(100.0 * SUM(CASE WHEN revol_util IS NULL OR trim(revol_util) = '' THEN 1 ELSE 0 END) / COUNT(*), 3) FROM stg_loans),
  (SELECT ROUND(100.0 * SUM(CASE WHEN revolving_util_pct IS NULL THEN 1 ELSE 0 END) / COUNT(*), 3) FROM cln_loans),
  'kept as NULL (not used in rates)'
UNION ALL SELECT 'loans', 'pub_rec_bankruptcies',
  (SELECT ROUND(100.0 * SUM(CASE WHEN TRY_CAST(pub_rec_bankruptcies AS INT) IS NULL THEN 1 ELSE 0 END) / COUNT(*), 3) FROM stg_loans),
  (SELECT ROUND(100.0 * SUM(CASE WHEN bankruptcies IS NULL THEN 1 ELSE 0 END) / COUNT(*), 3) FROM cln_loans),
  'kept as NULL'
UNION ALL SELECT 'loans', 'int_rate',
  (SELECT ROUND(100.0 * SUM(CASE WHEN TRY_CAST(replace(int_rate, '%', '') AS DOUBLE) IS NULL THEN 1 ELSE 0 END) / COUNT(*), 3) FROM stg_loans),
  (SELECT ROUND(100.0 * SUM(CASE WHEN int_rate_pct IS NULL THEN 1 ELSE 0 END) / COUNT(*), 3) FROM cln_loans),
  'required; percent sign stripped, cast to DOUBLE';

-- COMMAND ----------

CREATE OR REPLACE TABLE dq_issues AS
SELECT 'loans: duplicate or unusable rows removed' AS check_name,
       (SELECT COUNT(*) FROM stg_loans) - (SELECT COUNT(*) FROM cln_loans) AS affected_rows
UNION ALL SELECT 'loans: emp_length n/a (-> Unknown)', (SELECT SUM(dq_missing_emp_length) FROM cln_loans)
UNION ALL SELECT 'loans: revol_util missing', (SELECT SUM(dq_missing_revol_util) FROM cln_loans)
UNION ALL SELECT 'loans: home_ownership NONE/OTHER (-> OTHER)', (SELECT COUNT(*) FROM stg_loans WHERE trim(home_ownership) IN ('NONE', 'OTHER'))
UNION ALL SELECT 'loans: annual income outlier > Q3 + 3*IQR (kept, flagged)', (SELECT SUM(is_income_outlier_iqr3) FROM cln_loans)
UNION ALL SELECT 'loans: funded by investors < funded amount', (SELECT COUNT(*) FROM cln_loans WHERE funded_amount_investors < funded_amount - 0.01)
UNION ALL SELECT 'loans: still Current (excluded from default rates)', (SELECT SUM(1 - is_completed) FROM cln_loans)
UNION ALL SELECT 'loans: charged off with recoveries > 0', (SELECT COUNT(*) FROM cln_loans WHERE is_default = 1 AND recoveries > 0)
UNION ALL SELECT 'RI: fact without grade', (SELECT COUNT(*) FROM fact_loan WHERE grade_key IS NULL)
UNION ALL SELECT 'RI: fact without purpose', (SELECT COUNT(*) FROM fact_loan WHERE purpose_key IS NULL)
UNION ALL SELECT 'RI: fact without geography', (SELECT COUNT(*) FROM fact_loan WHERE geo_key IS NULL)
UNION ALL SELECT 'RI: fact without borrower profile', (SELECT COUNT(*) FROM fact_loan WHERE borrower_key IS NULL);

-- COMMAND ----------

CREATE OR REPLACE TABLE dq_assertions AS
WITH c AS (
  SELECT 'fact_loan.loan_id unique' AS check_name, (SELECT COUNT(*) - COUNT(DISTINCT loan_id) FROM fact_loan) AS failed_rows
  UNION ALL SELECT 'fact_loan.grade_key -> dim_grade', (SELECT COUNT(*) FROM fact_loan WHERE grade_key IS NULL OR grade_key NOT IN (SELECT grade_key FROM dim_grade))
  UNION ALL SELECT 'fact_loan.purpose_key -> dim_purpose', (SELECT COUNT(*) FROM fact_loan WHERE purpose_key IS NULL OR purpose_key NOT IN (SELECT purpose_key FROM dim_purpose))
  UNION ALL SELECT 'fact_loan.geo_key -> dim_geography', (SELECT COUNT(*) FROM fact_loan WHERE geo_key IS NULL OR geo_key NOT IN (SELECT geo_key FROM dim_geography))
  UNION ALL SELECT 'fact_loan.borrower_key -> dim_borrower', (SELECT COUNT(*) FROM fact_loan WHERE borrower_key IS NULL OR borrower_key NOT IN (SELECT borrower_key FROM dim_borrower))
  UNION ALL SELECT 'fact_loan.issue_month_key -> dim_date', (SELECT COUNT(*) FROM fact_loan WHERE issue_month_key NOT IN (SELECT month_key FROM dim_date))
  UNION ALL SELECT 'every state mapped to a census region', (SELECT COUNT(*) FROM dim_geography WHERE census_region = 'Unknown')
  UNION ALL SELECT 'term is 36 or 60 months', (SELECT COUNT(*) FROM fact_loan WHERE term_months NOT IN (36, 60))
  UNION ALL SELECT 'interest rate between 5% and 25%', (SELECT COUNT(*) FROM fact_loan WHERE int_rate_pct < 5 OR int_rate_pct > 25)
  UNION ALL SELECT 'dti between 0 and 30', (SELECT COUNT(*) FROM fact_loan WHERE dti < 0 OR dti >= 30)
  UNION ALL SELECT 'funded amount <= requested amount', (SELECT COUNT(*) FROM fact_loan WHERE funded_amount > loan_amount)
  UNION ALL SELECT 'sub_grade starts with grade', (SELECT COUNT(*) FROM dim_grade WHERE substr(sub_grade, 1, 1) <> grade)
  UNION ALL SELECT 'earliest credit line before issue month', (SELECT COUNT(*) FROM cln_loans WHERE earliest_credit_line >= issue_month)
  UNION ALL SELECT 'principal loss only on charged-off loans', (SELECT COUNT(*) FROM fact_loan WHERE principal_loss > 0 AND is_default = 0)
  UNION ALL SELECT 'grade default rates rise A -> G', (SELECT COUNT(*) FROM a_default_by_grade a JOIN a_default_by_grade b
                                                         ON b.grade_rank = a.grade_rank + 1 WHERE b.default_rate_pct < a.default_rate_pct)
)
SELECT check_name, failed_rows, CASE WHEN failed_rows = 0 THEN 'PASS' ELSE 'FAIL' END AS status FROM c;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## Quality summary
-- MAGIC All assertions should be PASS.

-- COMMAND ----------

SELECT * FROM dq_row_counts ORDER BY entity;

-- COMMAND ----------

SELECT * FROM dq_assertions ORDER BY status, check_name;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## Visualizations
-- MAGIC Run each cell, click **+ > Visualization** and configure as described. The same views are pre-built in `loan_default_dashboard.lvdash.json`.

-- COMMAND ----------

SELECT * FROM a_kpi_headline;

-- COMMAND ----------

-- Visualization: Default rate by grade
-- Bar: X = grade, Y = default_rate_pct (tooltip avg_int_rate_pct)
SELECT grade, loans, default_rate_pct, avg_int_rate_pct, net_return_pct FROM a_default_by_grade ORDER BY grade_rank;

-- COMMAND ----------

-- Visualization: Default rate by purpose
-- Horizontal bar: Y = purpose_label, X = default_rate_pct
SELECT purpose_label, loans, default_rate_pct, principal_loss FROM a_default_by_purpose ORDER BY default_rate_pct DESC;

-- COMMAND ----------

-- Visualization: Default rate by income band
-- Bar: X = income_band, Y = default_rate_pct
SELECT income_band, loans, default_rate_pct, median_income FROM a_default_by_income ORDER BY income_band;

-- COMMAND ----------

-- Visualization: Default rate by DTI band
-- Bar: X = dti_band, Y = default_rate_pct
SELECT dti_band, loans, default_rate_pct, avg_dti FROM a_default_by_dti ORDER BY dti_band;

-- COMMAND ----------

-- Visualization: Grade x DTI
-- Grouped bar: X = grade, Y = default_rate_pct, color = dti_band
SELECT grade, dti_band, loans, default_rate_pct FROM a_grade_dti_matrix ORDER BY grade, dti_band;

-- COMMAND ----------

-- Visualization: Vintage
-- Bar: X = issue_year, Y = loans (tooltip default_rate_pct)
SELECT issue_year, loans, funded, default_rate_pct, pct_60_month FROM a_vintage ORDER BY issue_year;
